version: '3.8'

services:
  sportapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=SportsNetworkingPlatform;Username=postgres;Password=admin
      - frontOfficeOrigin=http://localhost:4200
    volumes:
      - ./Images:/app/Images  # Map host directory ./Images to container directory /app/Images
    depends_on:
      postgres :
          condition: service_healthy
    networks:
      - mynetwork
    ports:
      - "8080:80"
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: SportsNetworkingPlatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - mynetwork
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./Images:/app/Images
      - /home/project/build:/usr/share/nginx/html
    depends_on:
      - sportapp
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true